services:
    php-fpm:
        build:
          context: .
          dockerfile: docker/fpm/Dockerfile
        volumes:
          - ./:/usr/src/app
          - ./system:/usr/src/app/system:rw,z
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
        volumes:
          - ./:/usr/src/app
          - ./system:/usr/src/app/system:rw,z
        ports:
          - 4501:80
        depends_on:
          - php-fpm
    mailer:
        image: schickling/mailcatcher
        ports:
          - 1025
          - 32770:1080